### ISSUE TITLE
INVITATIONS_ALLOWED_GROUPS is not optional

### ISSUE THREAD

**Issue by tbarbugli** [bee-keeper/django-invitations#10]
Hi,
It seems like running with INVITATIONS_ALLOWED_GROUPS=None (the default value) is not supported. the view at /invitations/send-invite/ raises the following exception:

```
ImproperlyConfigured at /invitations/send-invite/
SendInvite requires the "group_required" attribute to be set and be one of the following types: string, unicode, list or tuple```

**Comment by seanmavley** [comment]
Yeah, I get same error

**Comment by bee-keeper** [comment]
Thanks for raising this, I hadn't realised that 'group_required' was mandatory.  For now I have removed this from the package as it's simple enough to subclass the view if this functionality is needed.  

Since this is quite an annoying bug and I have 2 pull requests not yet in the package, I've just created a new release.
