### ISSUE TITLE
Group invitations

### ISSUE THREAD

**Issue by nwaxiomatic** [bee-keeper/django-invitations#13]
I had to recreate your app to handle invitations that auto-added the invited users to a set of groups.

Would this be an addition to the app of interest?

I basically just added a ManyToMany field called groups to the model and adjusted all templates/views/forms/admin to reflect the change.

**Comment by bee-keeper** [comment]
Hi,

Thanks for your offer to contribute but i think your use case here is too specific for a generic invitations app.  I am trying to keep the basic app as simple as possible so that it is easy to work with and adapt.

If you're looking to contribute in other ways may i suggest test coverage is pretty poor so I am definitely accepting pull requests in this area.
