### ISSUE TITLE
Posting via a URL

### ISSUE THREAD

**Issue by simonv3** [bee-keeper/django-invitations#3]
Instead of just having a form submission, is it possible to also post a URL? (enabling an ajax API).

**Comment by bee-keeper** [comment]
Hi there,

No this isn't built in right now but I agree it would be very useful.  

I'm currently working on a test suite and some bug fixes (see the devel branch) so that's my priority for now.  I anticipate I'll have this done quite soon and would definitely be interested in adding this functionality when time permits.  

Otherwise, please feel free to pull request - I would suggest implementing this in a similar model to [all-auth] (https://github.com/pennersr/django-allauth/blob/156a657fce1b5368adc17f3db7dea6f6cff64415/allauth/account/adapter.py#L269) as it makes it much easier for people working with both projects.

**Comment by simonv3** [comment]
I'll have a look at how all-auth handles similar things, and if I can find some time this week I'll try to do a PR. 

Thanks very much for this by the way, you've already saved me tons of time :)

**Comment by bee-keeper** [comment]
Merged - [#20](https://github.com/bee-keeper/django-invitations/pull/20)
