### ISSUE TITLE
Allow multiple invites per email

### ISSUE THREAD

**Issue by mahmoudhossam** [bee-keeper/django-invitations#62]
I'm trying to use django-invitations for a project which involves sending invites to people to join organizations modeled after Github organizations, but this app doesn't allow that behavior right now.

Can we leave up to the user to define whether they want to send multiple invites to the same email or not? possibly using a setting.

**Comment by matthewsewell** [comment]
I just forked and created something similar. What I've done so far is created a setting that, if set in the settings.py, will create a new migration removing the unique constraint. I then made modifications so that the invite can be accepted after someone logs in to an existing account.

I have not tested very thoroughly yet but it should be tested by mid week next week. Hopefully, once I'm done, they will accept my fork into the main project.

**Comment by matthewsewell** [comment]
I also just saw this was discussed elsewhere.

**Comment by clokep** [comment]
Just came across this, note that having a migration that's contingent on a setting isn't a good idea. It means that you have to account for two different database schemas in all the code you write and people will end up with different databases while using this package. I'd suggest trying to come up with a different way to do this!

**Comment by matthewsewell** [comment]
I agree that this solution is way less than optimal. The right way to do it is to abstract the model--which I think someone else is working on now. The solution I'm using is just a stop-gap for me right now.
