### ISSUE TITLE
feature request - add error message

### ISSUE THREAD

**Issue by nordbit** [bee-keeper/django-invitations#8]
And it will be nice add error message to display, if email address is in invitation table allready.

**Comment by bee-keeper** [comment]
There already is a message if the invitee has not accepted their invite.  However, I am working on adding more error messages.

**Comment by seanmavley** [comment]
For some reasons, mine doesn't show, I mean the error message. I understand there's a success_message sent to template, but for some reason I don't understand, it doesn't show. Perhaps, instead of re-rendering the template to the same page, rather there's a redirect when the form is successfully submitted.

**Comment by bee-keeper** [comment]
There's a test case now for this scenario and you can also use the admin form to send invitations.  In both cases the error messages are displayed.  @seanmavley I suspect the issue may be with your implementation, but in any case it's easy enough to swap out the form.  I'm going to close this for now, please feel free to open if you have further information relating to this issue.
