### ISSUE TITLE
use post save handler for invites instead of override create

### ISSUE THREAD

**Issue by tbarbugli** [bee-keeper/django-invitations#9]
I was reading the code and I was wondering why you implemented a create method for the invite class and not a post save callback. In my opinion save signals are the way to go (afaik create is not called when saving an instance with pk=None).

p.s. I can contribute a PR with this if you are willing to merge it ;)

**Comment by tbarbugli** [comment]
link to the relevant code: https://github.com/bee-keeper/django-invitations/blob/master/invitations/models.py#L32

**Comment by bee-keeper** [comment]
I'm not sure the advantage of changing this to signal and, in as much as possible, I'm trying to keep to the approach used by allauth [allauth](https://github.com/pennersr/django-allauth/blob/master/allauth/account/models.py) since this makes working with both packages a lot easier.  

Having said that, I'm not opposed to this approach but I'd also rather not make structural ie not bug fix changes until there's a lot more test coverage.
